### ISSUE TITLE
Xamarin IOS unable to get selected file

### ISSUE THREAD

**Issue by sandeepams** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#62] opened 2017-10-24 15:02 UTC
Hi @jfversluis ,
I've installed filepicker control from Nuget and added tried adding reference from MonoTouch10 folder and later from github to my xamarin.ios project.

1. FileData file = await  CrossFilePicker.Current.PickFile();
2. if (file != null) {  }

this is the code i added to my browse button, after selecting a file from iCloud drive, control never comes to 2. if condition.

and again when i click on browse button for second time, app crashes saying "only one operation can be active at a time".

**Comment by sandeepams** [comment] 2017-10-26 05:26
Hi @rafaelrmou, can u help me finding the solution for the above issue.

**Comment by ismailsameer12** [comment] 2017-11-07 10:30
hi sandeepams,
   correctly,i can't say this issue..
please use try and catch and you can see that kind of issues and solve them.

**Comment by iupchris10** [comment] 2017-11-14 21:27
Which version of iOS SDK are you using?  The iOS 11 SDK has deprecated the DidPickDocument callback, which may be the cause of this issue. This likely needs fixed in the plugin to support the new callback.

**Comment by sandeepams** [comment] 2017-11-15 06:55
I customized in plugin, like

Used "DocumentPicker_DidPickDocumentAtUrls" event instead of "DocumentPicker_DidPickDocument".
while returning selected file used

new FileData(e.FilePath, e.FileName, () => { var url = new Foundation.NSUrl(e.FilePath); return new FileStream(url.Path, FileMode.Open, FileAccess.Read); })
This solved my issue Thanks.

**Comment by carl-neng** [comment] 2017-11-28 03:34
Hi @sandeepams Can you tell us about add reference " adding reference from MonoTouch10 folder and later from github to my xamarin.ios project.". I'm tried to add it but not success. I hope you tell me step by step thank advance.

**Comment by carl-neng** [comment] 2017-11-28 14:08
Hi @sandeepams Can you show the details about event instead of "DocumentPicker_DidPickDocument".
while returning selected file used. Thank you advance.

**Comment by sandeepams** [comment] 2017-12-04 14:02
[FilePicker-Plugin-for-Xamarin-and-Windows-master.zip](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/files/1527338/FilePicker-Plugin-for-Xamarin-and-Windows-master.zip)

**Comment by carl-neng** [comment] 2017-12-05 02:27
Hi @sandeepams Thank you so much now it working fine.

**Comment by carl-neng** [comment] 2017-12-11 09:27
Hi @sandeepams When i'm using this dlls(Plugin.FilePicker.Abstractions && Plugin.FilePicker) I have problem with PNG file when I'm try to pickfile. It is show me don't have DataArray(byte).
Please help to this issue. Thank you
---- FileName ---
![image](https://user-images.githubusercontent.com/22851711/33824167-0abb81ce-de90-11e7-9e3b-ac63dd9b1d5e.png)

---- Debug Error -----
![image](https://user-images.githubusercontent.com/22851711/33824031-9a2ff3b8-de8f-11e7-83f4-17767f7dab03.png)

**Comment by sandeepams** [comment] 2017-12-11 09:50
Hi @carl-neng , just in case, could u please check the plugin code you r generating these dlls.
in FilePickerImplementation.cs file, under TakeMediaAsync() method make sure the handler code implemented this way.

 Handler = (s, e) =>
            {
                var tcs = Interlocked.Exchange(ref _completionSource, null);
                tcs?.SetResult(new FileData(e.FilePath, e.FileName, () =>
                {
                    var url = new Foundation.NSUrl(e.FilePath);
                    return new FileStream(url.Path, FileMode.Open, FileAccess.Read);
                }));
            };

**Comment by carl-neng** [comment] 2017-12-11 10:18
Hi @sandeepams Yes exactly, I use like this. Because I has been downloaded your sample you give with zip file. And I'm try use it again..... so what I can do please help.

![image](https://user-images.githubusercontent.com/22851711/33826337-38c4d74e-de97-11e7-9d01-a0f43ba0a7ae.png)

**Comment by carl-neng** [comment] 2017-12-12 02:11
Hi @sandeepams Yes sure, and have problem when we selected the same file for two time.

**Comment by sandeepams** [comment] 2017-12-12 16:05
@carl-neng , Today also i tested my app, accepting PNG files and accepting same file multiple times, may be rebuild issue of plugin. could you please try clean rebuild plugin and import new dlls?

**Comment by jfversluis** [comment] 2017-12-29 00:49
This should now be working in this NuGet: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.0-beta

If not, please open a issue on the new repo where development will be continued: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues

**Closed by jfversluis** 2017-12-29 00:49 UTC
